import { Fredoka, Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

import { LocaleProvider } from "@/context/LocaleContext";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-fredoka",
});

const exo = Exo({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-exo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LocaleProvider>
      <html lang="en">
        <body
          className={`${fredoka.variable} ${exo.variable} antialiased flex`}
        >
          <main className="w-full min-h-screen bg-neutral-900">{children}</main>
        </body>
      </html>
    </LocaleProvider>
  );
}
